animations {
    enabled = true

		bezier = heavyOvershoot, 0.53, 0.51, 0.3, 1.22
		bezier = lightOvershoot, 0.33, 0.61, 0.63, 1.19
		bezier = smoothSnap, 0.32, 0.51, 0.44, 1
		bezier = smoothIn, 0.25, 1, 0.5, 1
		bezier = smoothOutOvershoot, 0.46, -0.25, 0.81, 0.51

		animation = workspaces, 1, 2.5, heavyOvershoot, slidefade 30%
		animation = specialWorkspace, 1, 2, smoothIn, slidefadevert -80%
		animation = specialWorkspaceOut, 1, 1.7, smoothOutOvershoot, slidefadevert -80%

		animation = windows, 1, 2, smoothIn, slide right
		animation = windowsMove, 1, 2, smoothSnap
		animation = windowsOut, 1, 4, heavyOvershoot, popin 30%

		animation = fade, 1, 2, smoothIn
}
