# Script Path
$scrPath = ~/.config/scripts

# Assign apps
$term = kitty
$file = nemo
$browser = firefox
$launcher = $scrPath/otter-launch.sh

# Window/Session actions
bind = $mainMod, backspace, exec, $scrPath/dontkillsteam.sh # close focused window
bind = $mainMod, d, exec, $launcher

# Super key to drag windows
binds {
    drag_threshold = 10
    scroll_event_delay = 0
}
bindm = $submod, mouse:272, movewindow
bindr = $submod, mouse:272, layoutmsg, promote
bindc = $submod, mouse:272, togglefloating

# Resize floating window with scrollwheels
bind = $submod, mouse_down, resizeactive, 0 -30
bind = $submod, mouse_up, resizeactive, 0 30
bind = $submod, mouse_left, resizeactive, 30 0
bind = $submod, mouse_right, resizeactive, -30 0
bind = $submod, space, togglefloating, # toggle the window between focus and float

# Screenshot/Screencapture
bind = Super+SHIFT, S, exec, grimblast copy area

# Move/Change window focus
bind = $mainMod, h, layoutmsg, focus l
bind = $mainMod, l, layoutmsg, focus r
bind = $mainMod, k, movefocus, u
bind = $mainMod, j, movefocus, d

# Resize floating windows with keyboard
bind = $submod ctrl, h, resizeactive, -50 0
bind = $submod ctrl, l, resizeactive, 50 0
bind = $submod ctrl, k, resizeactive, 0 50
bind = $submod ctrl, j, resizeactive, 0 -50

# Change window positions with keyboard
bind = $mainMod SHIFT, H, swapwindow, l
bind = $mainMod SHIFT, L, swapwindow, r
bind = $mainMod SHIFT, K, swapwindow, u
bind = $mainMod SHIFT, J, swapwindow, d

# Move/Switch to special workspace (scratchpad)
bind = $mainMod, MINUS, togglespecialworkspace, scratch
bind = $mainMod SHIFT, MINUS, movetoworkspacesilent, special:scratch

# Music workspace
bind = $mainMod, m, togglespecialworkspace, music

source = ~/.config/hypr/binds-local.conf
