input {
    kb_layout = gb
    follow_mouse = 1

    touchpad {
        natural_scroll = true
        disable_while_typing = true
    }

    sensitivity = -0.3
    force_no_accel = false
		tablet {
			left_handed = true
			output = current
		}
}

cursor {
    inactive_timeout = 2
		warp_on_change_workspace = 1
		hide_on_key_press = true
		warp_on_toggle_special = 1
}

device {
	name = 2.4g-wireless-optical-mouse--mouse
	sensitivity = -0.65
	accel_profile = adaptive
}

device {
	name = wacom-bamboo-16fg-4x5-finger
	flip_x = true
	flip_y = true
	natural_scroll = false
	sensitivity = 0.3
	accel_profile = adaptive
}
