windowrule {
  name = nodim-youtube
  no_dim = on
  opaque = on
  match:class = ^(firefox|Firefox)$
  match:title = ^(.*YouTube.*)$
}

windowrule {
  name = nodim-delfin
  no_dim = on
  opaque = on
  match:class = ^(cafe.avery.Delfin)$
}

windowrule {
  name = float-firefoxDialogue
  float = on
  match:title = ^(About Mozilla Firefox)$
}

windowrule {
  name = file-browser
  float = on
  size = 800 500
  animation = popin
  match:class = ^(xdg-desktop-portal-gtk)$
}

windowrule {
  name = firefox-pip
  float = on
  match:class = ^(firefox)$
  match:title = ^(Picture-in-Picture)$
}

windowrule {
  name = float-history
  float = on
  match:class = ^(firefox)$
  match:title = ^(Library)$
}

windowrule {
  name = nwg-look
  float = on
  match:class = ^(nwg-look)$
}

windowrule {
  name = volume-control
  float = on
  match:class = ^(org.pulseaudio.pavucontrol)$
}

windowrule {
  name = blueman-size
  float = on
  size = 600 400
  animation = popin
  match:class = ^(.blueman-manager-wrapped)$
}

windowrule {
  name = float-nm
  float = on
  match:class = ^(nm-applet)$
}

windowrule {
  name = float-nm
  float = on
  match:class = ^(nm-connection-editor)$
}

windowrule {
  name = float-auth-agent
  float = on
  match:class = ^(org.kde.polkit-kde-authentication-agent-1)$
}

windowrule {
  name = firefox-popups
  size = 800 500
  animation = popin
  match:class = ^(firefox)$
  match:title = ^(.*Save.*)
}

windowrule {
  name = otter-launcher-initial
  size = 425 220
	float = on
	opaque = on
  animation = popin 50%
  match:class = ^(otter)$
}

windowrule {
  name = jellyfin tui
  animation = slide top
  match:class = ^(jf-tui)$
}

windowrule {
	name = nodim-fullscreen
	match:fullscreen = 1
	no_dim = on
}

windowrule {
	name = nodim-kitty
  match:class = ^(kitty)$
	opaque = on
	xray = on
}

layerrule {
  name = layerrule-1
  blur = on
  ignore_alpha = 0
  match:namespace = notifications
}

layerrule {
  name = something to do with wlogout
  blur = on
  match:namespace = logout_dialog
}

layerrule {
  name = layerrule-3
  blur = on
	ignore_alpha = 0
  match:namespace = waybar
}

layerrule {
  name = layerrule-4
  ignore_alpha = 0
  blur = on
  animation = popin 70%
  match:namespace = otter-panel
}

layerrule {
  name = layerrule-5
  animation = slide right
  blur = on
  ignore_alpha = 0
  match:namespace = swaync-control-center
}

workspace = special:music, gapsout:5 400 400 400
workspace = special:scratch, gapsout:20 20 20 20
